version: '3.2'
services:
    api:
        build: ./homework-eb-be/.
        command: "nodemon ../server/server.js"        
        volumes:
            - ./homework-eb-be:/app
        ports:
            - "3000:3000" 
        networks:
            - homework
    react:
        build: ./homework-eb-fe/.
        ports:
              - '80:80'
        networks:
            - homework
volumes:
    libreos-db:
        external: true
networks:
    homework:
        external: false
